on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "http://localhost:3000/api/reset-database?token=${RESET_TOKEN}"
        env:
          RESET_TOKEN: ${{secrets.RESET_TOKEN}}
